src/toudou/views.py
"""
    This module contains the routes for the Toudou app web interface
"""
from flask import Flask, abort, flash, redirect, render_template, request, send_file, Blueprint, url_for
from datetime import datetime
import uuid, os, logging
from toudou import services, config
from toudou.web_views.forms import AddForm, UpdateForm, DeleteForm
from toudou.web_views.auth import auth

import toudou.models as models


web_ui = Blueprint('web_ui', __name__, url_prefix="/")


# Routes

@web_ui.route("/error/<code>", methods=["GET", "POST"])
def error(code):
    """
        Render the error page

        - Args :
            - code (str) : the error code

        - Returns :
            - (str) : the HTML for the error page
    """
    return render_template(f"error.html", role=auth.get_user_roles(auth.username()), error=code)


@web_ui.route("/", defaults={"page": "index"})
@web_ui.route("/<page>")
@auth.login_required
def show(page):
    """
        Render the requested page

        - Args :
            - page (str) : the page to render

        - Returns :
            - (str) : the HTML for the requested page
    """
    if os.path.exists(os.path.join("src", "toudou", "templates", f"{page}.html")):
        if "user" in auth.get_user_roles(auth.username()) and page not in ("index", "export"):
            abort(403)
        
        else :
            logging.info(f"Rendering {page}.html")
            return render_template(f"{page}.html", todos=models.get_all_todos(), add_form=AddForm(), update_form=UpdateForm(), delete_form=DeleteForm(), role=auth.get_user_roles(auth.username()))
    else:
        abort(404)


@web_ui.route("/controller", methods=["GET", "POST"])
@auth.login_required
def controller():
    """
        The controller for the Toudou app that handles GET and POST requests

        - Args :
            - None

        - Returns :
            - (str) : the HTML for the index page
    """
    if "admin" in auth.get_user_roles(auth.username()):
        if request.method == "POST":
            if request.form.get('action') == "add":
                form = AddForm()
                if form.validate_on_submit():
                    logging.info(f"Adding a new Todo: {request.form.get('task', '')}")
                    models.create_todo(request.form.get('task', ''), due=((datetime.strptime(request.form.get('due', ''), "%Y-%m-%d")).date() if request.form.get('due') else None)) # type: ignore
                else:
                    return redirect(url_for('web_ui.show'))
                
            elif request.form.get('id', ''):
                if request.form.get('action') == "update":
                    form = UpdateForm()
                    new_comp = False
                    if request.form.get('complete'):
                        new_comp = True
                    if form.validate_on_submit():
                        logging.info(f"Updating Todo: {request.form.get('task', '')}")
                        models.update_todo(uuid.UUID(request.form.get('id', '')), request.form.get('task', ''), new_comp, due=((datetime.strptime(request.form.get('due', ''), "%Y-%m-%d")).date() if request.form.get('due') else None)) # type: ignore
                    else:
                        return redirect(url_for('web_ui.show'))
                
                elif request.form.get('action') == "delete":
                    form = DeleteForm()
                    if form.validate_on_submit():
                        logging.info(f"Deleting Todo: {request.form.get('id', '')}")
                        models.delete_todo(uuid.UUID(request.form.get('id', '')))
                    else:
                        return redirect(url_for('web_ui.show'))
        
            elif request.files:
                file = request.files["file"]

                filename = os.path.join(config['UPLOAD_FOLDER'], file.filename)
                file.save(filename)
                file = open(filename)
                logging.info(f"Importing Todos from CSV: {filename}")
                services.import_from_csv(file)
                file.close()
                
    return redirect(url_for('web_ui.show'))


@web_ui.route("export/")
@auth.login_required
def export():
    """
        Download the CSV file of all the Todos

        - Args :
            - None

        - Returns :
            - (file) : the CSV file of all the Todos
    """
    logging.info(f"Exporting Todos to CSV")
    path = "../../" + services.export_to_csv()
    return send_file(path, as_attachment=True)


@web_ui.route("out/")
def out():
    """
        Log out the user

        - Args :
            - None

        - Returns :
            - (str) : the HTML for the index page
    """
    logging.info(f"Logging out user {auth.username()}")

    # We get the listening port to redirect to the correct URL
    port = request.environ.get('SERVER_PORT')

    # We redirect to the index page with false credentials
    return redirect("http://nouser:nouser@localhost:" + str(port) + "/")


# Error Handlers

@web_ui.errorhandler(401)
def handle_401(error):
    """
        Handle 401 errors
        
        - Args :
            - error (str) : the error message

        - Returns :
            - (str) : the HTML for the error page
    """
    flash("401: Unauthorized")
    logging.exception(error)
    return redirect(url_for('web_ui.error', code=401))


@web_ui.errorhandler(403)
def handle_403(error):
    """
        Handle 403 errors

        - Args :
            - error (str) : the error message

        - Returns :
            - (str) : the HTML for the error page
    """
    flash("403: Forbidden")
    logging.exception(error)
    return redirect(url_for('web_ui.error', code=403))


@web_ui.errorhandler(404)
def handle_404(error):
    """
        Handle 404 errors

        - Args :
            - error (str) : the error message

        - Returns :
            - (str) : the HTML for the error page
    """
    flash("404: Page not found")
    logging.exception(error)
    return redirect(url_for('web_ui.error', code=404))


@web_ui.errorhandler(405)
def handle_405(error):
    """
        Handle 405 errors

        - Args :
            - error (str) : the error message

        - Returns :
            - (str) : the HTML for the error page
    """
    flash("405: Method Not Allowed")
    logging.exception(error)
    return redirect(url_for('web_ui.error', code=405))


@web_ui.errorhandler(500)
def handle_500(error):
    """
        Handle 500 errors

        - Args :
            - error (str) : the error message

        - Returns :
            - (str) : the HTML for the error page
    """
    flash("500: Internal Server Error")
    logging.exception(error)
    return redirect(url_for('web_ui.error', code=500))


def create_app():
    """
        Create the Flask app instance

        - Args :
            - None

        - Returns :
            - (Flask) : the Flask app instance
    """
    app = Flask(__name__)
    app.config['SECRET_KEY'] = config['SECRET_KEY']
    from toudou.views import web_ui
    from toudou.api.routes import api, spec
    spec.register(app)
    app.register_blueprint(web_ui)
    app.register_blueprint(api)
    return app

src/toudou/templates/error.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style/theme.css') }}">
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='resources/favicon.ico') }}">
    <title>Error {{ error }}</title>
</head>

<body>
    {% include 'header.html' %}

    <h1>Error {{ error }}</h1>

    <h2>
        {% if error|int == 401 %}
            You must be logged in to access this resource
        {% elif error|int == 403 %}
            You do not have permission to access this resource
        {% elif error|int == 404 %}
            The page you are looking for does not exist
        {% else %}
            There has been an error processing your request
        {% endif %}
    </h2>
</body>

src/toudou/templates/header.html
<header>
    <h1>Todo app</h1>
    <hr>
    <nav>
        <a href="{{ url_for('web_ui.show') }}">Home</a>
        <a href="{{ url_for('web_ui.export') }}">Export csv</a>
        {% if 'admin' in role %}
            <a href="{{ url_for('web_ui.show', page='import') }}">Import csv</a>
        {% endif %}
        <a href="{{ url_for('web_ui.out') }}">Log out</a>
    </nav>
</header>

src/toudou/templates/import.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style/theme.css') }}">
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='resources/favicon.ico') }}">
    <title>Import csv</title>
</head>

<body>
    {% include 'header.html' %}

    <h1>Upload a csv file to add tasks</h1>

    <form method="POST" enctype="multipart/form-data" id="upload_form" action="{{ url_for('web_ui.controller') }}">
        <input type="hidden" name="action" value="upload">
        <input type="file" name="file" id="file" accept=".csv" required>
        <input type="submit" value="Upload csv" class="sub_input">
    </form>
</body>

src/toudou/templates/index.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style/theme.css') }}">
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='resources/favicon.ico') }}">
    {% if 'admin' in role %}
        <script src="{{ url_for('static', filename='scripts/update.js') }}"></script>
    {% endif %}
    <title>Home</title>
</head>

<body>
    {% include 'header.html' %}

    <h1>Here are your tasks !</h1>

    <div id="main_frame">
    {% if todos %}
        <table>
            <tr>
                <th>ID</th>
                <th>Due</th>
                <th>Task</th>
                <th id="small_th">Complete</th>
            </tr>

            {% for todo in todos %}
                <tr id= {{todo.id}}>
                    <td>{{ todo.id }}</td>
                    {% if todo.due %}
                        <td class="due">{{ todo.due.strftime('%d / %m / %Y') }}</td>
                    {% else %}
                        <td class="due">None</td>
                    {% endif %}
                    <td>{{ todo.task }}</td>
                    {% if todo.complete %}
                        <td class="task_done">Yes</td>
                    {% else %}
                        <td class="task_not_done">No</td>
                    {% endif %}
                </tr>
            {% endfor %}
        </table>

    {% else %}
        <h1>You have no tickets !</h1>
    {% endif %}

    {% if 'admin' in role %}
        <div id="todos_edit">

            <form class="edit_todo" id="add_form" method="POST" action="{{ url_for('web_ui.controller') }}">
                {{ add_form.csrf_token }}
                <h2>Add a new task</h2>
                {{ add_form.task(class='task_field', placeholder='New task') }}
                {{ add_form.due(class='task_field') }}
                <br>
                {{ add_form.action(value='add') }}
                <input type="reset" value="Reset">
                <input type="submit" value="Add task" class="sub_input">
            </form>

            <div class="edit_todo">
                <form method="POST" id="update_form" action="{{ url_for('web_ui.controller') }}">
                    {{ update_form.csrf_token }}
                    <h2>Edit this task</h2>
                    <h3 id="id_title">No task</h3>
                    {{ update_form.task(class='task_field', id='update_task', placeholder='Edit task') }}
                    {{ update_form.due(class='task_field', id='update_due') }}
                    <div id="comp_check">
                        <label for="update_comp">Complete :</label>
                        {{ update_form.complete(value='complete', id='update_comp') }}
                    </div>
                    <br>
                    {{ update_form.action(value='update') }}
                    {{ update_form.id(class='update_id') }}
                    <input type="reset" value="Reset">
                    <input type="submit" value="Edit" class="sub_input">
                </form>
                <br>
                <form method="POST" action="{{ url_for('web_ui.controller') }}">
                    {{ delete_form.csrf_token }}
                    {{ delete_form.action(value='delete') }}
                    {{ delete_form.id(class='update_id') }}
                    <input type="submit" value="Delete" class="del_input">
                </form>
            </div>

        </div>
    {% endif %}

    </div>
</body>
</html>

src/toudou/templates/upload.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <link rel="stylesheet" type="text/css" href="{{ url_for('static', filename='style/theme.css') }}">
    <title>Upload csv</title>
</head>

<body>
    {% include 'header.html' %}

    <h1>Upload a csv file to add tasks</h1>

    <form method="POST" enctype="multipart/form-data" id="upload_form" action="{{ url_for('index') }}">
        <input type="hidden" name="action" value="upload">
        <input type="file" name="file" id="file" accept=".csv" required>
        <input type="submit" value="Upload csv" class="sub_input">
    </form>
</body>